function [im,h] = readnii(niifile_name,varargin)
% function [im,h] = readnii(niifile_name)
%
% Part of umasl project by Luis Hernandez-Garcia and David Frey
% @ University of Michigan 2022
%
% Description: Function to read nii image file into Nd image array
%
%
% Notes:
%   - no defaults on input arguments, all arguments are required
%
% Dependencies:
%   - matlab default path
%       - can be restored by typing 'restoredefaultpath'
%   - umasl
%       - github: fmrifrey/umasl
%       - umasl/matlab/ and subdirectories must be in current path
%
% Static input arguments:
%   - niifile_name:
%       - name of nii file to read from
%       - string describing file path/name
%       - if string does not include '.nii', it will be automatically
%           appended
%       - no default, necessary argument
%
% Variable input arguments (type 'help varargin' for usage info):
%   - 'readcomplex':
%       - option to read complex data as written by writenii()
%       - boolean integer (0 or 1) describing whether or not to use
%       - data will be read from two seperate files: '*_mag.nii' and
%           '*_ang.nii' for magnitude and phase, respectively
%       - default is 1
%
% Function outputs:
%   - im:
%       - output image
%       - double/float image array of N dimensions
%       - image will be automatically scaled and reshaped based on header
%   - h:
%       - nifti header structure
%

    % Define default arguments
    defaults = struct( ...
        'readcomplex',  1 ...
        );

    % Parse through variable inputs using matlab's built-in input parser
    args = vararginparser(defaults,varargin{:});

    % Remove .nii extension if included
    if contains(niifile_name,'.nii')
        niifile_name = strsplit(niifile_name,'.nii');
        niifile_name = niifile_name{1};
    end

    % Recurse if complex
    if args.readcomplex && ...
            isfile([niifile_name,'_mag.nii']) &&  ...
            isfile([niifile_name,'_ang.nii'])
        im = readnii([niifile_name,'_mag']) .* ...
            exp(1i*readnii([niifile_name,'_mag']));
    else
        % Open nifti file for reading
        [niifile,msg_fopen] = fopen([niifile_name,'.nii'],'r','ieee-le');
        if ~isempty(msg_fopen), error(msg_fopen); end

        % Read in header
        h = makeniihdr(...
            'sizeof_hdr',       fread(niifile, 1,'int32')', ...	% should be 348!
            'data_type',        fread(niifile,10,'*char')', ...
            'db_name',          fread(niifile,18,'*char')',...
            'extents',          fread(niifile, 1,'int32')', ...
            'session_error',    fread(niifile, 1,'int16')', ...
            'regular',          fread(niifile, 1,'*char')', ...
            'dim_info',         fread(niifile, 1,'*char')', ...
            'dim',              fread(niifile,8,'int16')', ...
            'intent_p1',        fread(niifile,1,'float32')', ...
            'intent_p2',        fread(niifile,1,'float32')', ...
            'intent_p3',        fread(niifile,1,'float32')', ...
            'intent_code',      fread(niifile,1,'int16')', ...
            'datatype',         fread(niifile,1,'int16')', ...
            'bitpix',           fread(niifile,1,'int16')', ...
            'slice_start',      fread(niifile,1,'int16')', ...
            'pixdim',           fread(niifile,8,'float32')', ...
            'vox_offset',       fread(niifile,1,'float32')', ...
            'scl_slope',        fread(niifile,1,'float32')', ...
            'scl_inter',        fread(niifile,1,'float32')', ...
            'slice_end',        fread(niifile,1,'int16')', ...
            'slice_code',       fread(niifile,1,'*char')', ...
            'xyzt_units',       fread(niifile,1,'*char')', ...
            'cal_max',          fread(niifile,1,'float32')', ...
            'cal_min',          fread(niifile,1,'float32')', ...
            'slice_duration',   fread(niifile,1,'float32')', ...
            'toffset',          fread(niifile,1,'float32')', ...
            'glmax',            fread(niifile,1,'int32')', ...
            'glmin',            fread(niifile,1,'int32')', ...
            'descrip',          fread(niifile,80,'*char')', ...
            'aux_file',         fread(niifile,24,'*char')', ...
            'qform_code',       fread(niifile,1,'int16')', ...
            'sform_code',       fread(niifile,1,'int16')', ...
            'quatern_b',        fread(niifile,1,'float32')', ...
            'quatern_c',        fread(niifile,1,'float32')', ...
            'quatern_d',        fread(niifile,1,'float32')', ...
            'qoffset_x',        fread(niifile,1,'float32')', ...
            'qoffset_y',        fread(niifile,1,'float32')', ...
            'qoffset_z',        fread(niifile,1,'float32')', ...
            'srow_x',           fread(niifile,4,'float32')', ...
            'srow_y',           fread(niifile,4,'float32')', ...
            'srow_z',           fread(niifile,4,'float32')', ...
            'intent_name',      fread(niifile,16,'*char')', ...
            'magic',            fread(niifile,4,'*char')', ...
            'originator',       fread(niifile, 5,'int16'),...
            'esize',            0, ...
            'ecode',            0, ...
            'edata',            '' ...
            );

        % Read in data
        fseek(niifile,h.vox_offset,'bof');
        im = fread(niifile, prod(h.dim(2:5)), niidatatype(h.datatype))';
        fclose(niifile);

        % Reshape and rescale data
        im = reshape(im,h.dim(2:5));
        im = h.scl_slope*im + h.scl_inter;
    end

end

